language: ruby
rvm:
  - 1.9.3
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec
  - RAILS_ENV=test bundle exec rake stats
before_install:
  - "export DISPLAY=:99.0"
  - "export BUNDLE_JOBS=4"
  - "export IS_TRAVIS=true"
  - "sh -e /etc/init.d/xvfb start"
bundler_args: --without development --deployment
