language: ruby
rvm:
  - 1.9.3
  - 2.1.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec
  - RAILS_ENV=test bundle exec rake stats
  - RAILS_ENV=test bundle exec rake teaspoon
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
  - "export DISPLAY=:99.0"
  - "export BUNDLE_JOBS=4"
  - "export COVERAGE=true"
  - "export COVERALLS=true"
  - "sh -e /etc/init.d/xvfb start"
  - "./script/get_bundler.sh"
bundler_args: --without development --deployment
cache:
  - bundler
  - apt
